### PR TITLE
Update CrLF on all py files,  second part is move from csv to json.

### PR DESCRIPTION
**Pull request by iplayfast**
no changes other then line endings. (it looks like a lot but no code was actually changed).

### CODE REVIEW

**Comment by iplayfast** [comment]
Reverted back to yanniedog's and then added his changes, then fixed crlfs.

**Comment by iplayfast** [comment]
csv to json part of merge

**Comment by yanniedog** [comment]
Just wanted to let you know I'm still working on this. I'll push a forked version of what I'm working on at the moment. I'm trying to get an feel for whether the results are actually better with JSON or CSV. Not sure yet. The LLM always seems to find creative ways to mess up the structure

**Comment by yanniedog** [comment]
Work in progress:

https://github.com/yanniedog/autocrew/tree/JSON-experimental

**Comment by yanniedog** [comment]
Urgh... making the conversion from CSV to JSON is proving a bit more difficult than expected

**Comment by yanniedog** [comment]
I can't accept this PR into main at the moment because it's too unstable. However, I'm moving the PR into this branch: https://github.com/yanniedog/autocrew/tree/testing

**Pull request merged**
