### PR TITLE
Updated lot'so code so that json is used instead of CSV

### PR DESCRIPTION
**Pull request by iplayfast**
I've found that LLM's format json much better then csv's and it looked like a lot of work was being done to fix csv output into something manageable. 
Very cool project!

### CODE REVIEW

**Comment by yanniedog** [comment]
Thanks you for your kind words and great effort here. Yes, I agree, JSON is probably a more reliable option than CSVs. The response from the LLM looked good, but the validation threw an error.
I'm happy to implement this once we test it and iron out the bugs (as seen here):

[autocrew.log](https://github.com/yanniedog/autocrew/files/14124930/autocrew.log)

**Comment by iplayfast** [comment]
Changed CRLF's at end of lines. (driving me mad)
Allowed 3 retries when talking to LLM, as I believe the error you saw was the LLM not giving a good response.

**Comment by iplayfast** [comment]
Hmm, the crlf issue makes all files unmergable I'm going to redo this pull, so ignore it for now.

**Comment by yanniedog** [comment]
> Changed CRLF's at end of lines. (driving me mad)
> Allowed 3 retries when talking to LLM, as I believe the error you saw was the LLM not giving a good response.
> 

It should be retrying 10 times...this function appears to have disappeared

**Pull request closed without merging**
